services:
  app:
    build: .
    ports:
      - "5456:5456"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hr_management
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kwizera23
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hr-network
    volumes:
      - ./uploads:/app/uploads

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=hr_management
      - MYSQL_ROOT_PASSWORD=Kwizera23
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  hr-network:
    driver: bridge

volumes:
  mysql-data:
