version: '3.8'

services:
  app:
    build: .
    ports:
      - "5456:5456"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hr_management
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kwizera23
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - hr-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=hr_management
      - MYSQL_ROOT_PASSWORD=Kwizera23
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge

volumes:
  mysql-data:
