package com.hr_management.hr.model;

import java.time.LocalDate;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class HolidayDto {
    
    // ID is not needed for creation, it will be generated by the database
    private Long id;
    
    @NotBlank(message = "Holiday name is required")
    private String name;
    
    @NotNull(message = "Holiday date is required")
    private LocalDate date;
    
    private String description;
    
    private boolean recurring;
    
    // These fields are managed by the system, not needed for creation
    private String createdBy;
    private LocalDate createdAt;
    private LocalDate updatedAt;

    // Default constructor
    public HolidayDto() {
    }

    // All-args constructor
    public HolidayDto(Long id, String name, LocalDate date, String description, 
                     boolean recurring, String createdBy, LocalDate createdAt, LocalDate updatedAt) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.description = description;
        this.recurring = recurring;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private Long id;
        private String name;
        private LocalDate date;
        private String description;
        private boolean recurring;
        private String createdBy;
        private LocalDate createdAt;
        private LocalDate updatedAt;

        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder date(LocalDate date) {
            this.date = date;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder recurring(boolean recurring) {
            this.recurring = recurring;
            return this;
        }

        public Builder createdBy(String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        public Builder createdAt(LocalDate createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder updatedAt(LocalDate updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public HolidayDto build() {
            return new HolidayDto(id, name, date, description, recurring, createdBy, createdAt, updatedAt);
        }
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isRecurring() {
        return recurring;
    }

    public void setRecurring(boolean recurring) {
        this.recurring = recurring;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDate getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDate createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDate getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDate updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        HolidayDto that = (HolidayDto) o;
        return recurring == that.recurring &&
                (id != null ? id.equals(that.id) : that.id == null) &&
                (name != null ? name.equals(that.name) : that.name == null) &&
                (date != null ? date.equals(that.date) : that.date == null) &&
                (description != null ? description.equals(that.description) : that.description == null) &&
                (createdBy != null ? createdBy.equals(that.createdBy) : that.createdBy == null) &&
                (createdAt != null ? createdAt.equals(that.createdAt) : that.createdAt == null) &&
                (updatedAt != null ? updatedAt.equals(that.updatedAt) : that.updatedAt == null);
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (date != null ? date.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + (recurring ? 1 : 0);
        result = 31 * result + (createdBy != null ? createdBy.hashCode() : 0);
        result = 31 * result + (createdAt != null ? createdAt.hashCode() : 0);
        result = 31 * result + (updatedAt != null ? updatedAt.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "HolidayDto{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", date=" + date +
                ", description='" + description + '\'' +
                ", recurring=" + recurring +
                ", createdBy='" + createdBy + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
} 